development:  
  adapter: postgresql
  encoding: unicode
  database: team_dev
  pool: 5
  username: matiasdim
  password:

test:  
  adapter: postgresql
  encoding: unicode
  database: team_test
  pool: 5
  username: matiasdim
  password: